language: php

php:
  - 7.2
  - 7.3
  - master

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

sudo: false

before_install:
  - composer self-update
  - composer clear-cache
  - wget https://phar.phpunit.de/phpunit-7.5.phar

install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable --prefer-lowest; fi

script:
  - php phpunit.phar

notifications:
  email: false

